
package br.telefonica.gonext.nginservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NGINServicesImplService", targetNamespace = "http://telefonica.br/GONext/NGINServices", wsdlLocation = "http://sv2kpvbpl1:8001/NGINServicesImpl/NGINServicesImplService?wsdl")
public class NGINServicesImplService
    extends Service
{

    private final static URL NGINSERVICESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NGINSERVICESIMPLSERVICE_EXCEPTION;
    private final static QName NGINSERVICESIMPLSERVICE_QNAME = new QName("http://telefonica.br/GONext/NGINServices", "NGINServicesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sv2kpvbpl1:8001/NGINServicesImpl/NGINServicesImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NGINSERVICESIMPLSERVICE_WSDL_LOCATION = url;
        NGINSERVICESIMPLSERVICE_EXCEPTION = e;
    }

    public NGINServicesImplService() {
        super(__getWsdlLocation(), NGINSERVICESIMPLSERVICE_QNAME);
    }

    public NGINServicesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NGINSERVICESIMPLSERVICE_QNAME, features);
    }

    public NGINServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, NGINSERVICESIMPLSERVICE_QNAME);
    }

    public NGINServicesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NGINSERVICESIMPLSERVICE_QNAME, features);
    }

    public NGINServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NGINServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NGINServicesWS
     */
    @WebEndpoint(name = "NGINServicesWSPort")
    public NGINServicesWS getNGINServicesWSPort() {
        return super.getPort(new QName("http://telefonica.br/GONext/NGINServices", "NGINServicesWSPort"), NGINServicesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NGINServicesWS
     */
    @WebEndpoint(name = "NGINServicesWSPort")
    public NGINServicesWS getNGINServicesWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://telefonica.br/GONext/NGINServices", "NGINServicesWSPort"), NGINServicesWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NGINSERVICESIMPLSERVICE_EXCEPTION!= null) {
            throw NGINSERVICESIMPLSERVICE_EXCEPTION;
        }
        return NGINSERVICESIMPLSERVICE_WSDL_LOCATION;
    }

}
